# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('What', models.CharField(max_length=500)),
                ('When', models.CharField(max_length=500)),
                ('Where', models.CharField(max_length=500)),
                ('Done', models.CharField(max_length=250)),
            ],
        ),
    ]
